# Generated by Django 4.2.3 on 2023-07-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Commande'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Detail de commande', 'verbose_name_plural': 'Details des commandes'},
        ),
        migrations.DeleteModel(
            name='ProductHasCart',
        ),
    ]
