# Generated by Django 4.2.3 on 2023-07-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopper',
            options={},
        ),
        migrations.AlterModelManagers(
            name='shopper',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='password',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='username',
        ),
        migrations.AddField(
            model_name='shopper',
            name='name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='shopper',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='email',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
